#!/usr/bin/env python3

# TODO
from helpers import get_user_timeline
import sys
import os
from analyzer import Analyzer
from termcolor import colored

def main():
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
    tweets = get_user_timeline(sys.argv[1], 50)
    
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    for tweet in tweets:
        emotion = analyzer.analyze(tweet)
        if emotion > 0:
            color = "green"
        elif emotion < 0:
            color = "red"
        else:
            color = "yellow"
        print(colored("{} {}".format(emotion, tweet), color))
        
    
if __name__ == "__main__":
    main()